### ISSUE TITLE
Don't use default (unnamed) package.

### ISSUE THREAD

**Issue by nilskp** [danielshaya/ByteWatcher#1]
I'm unable to use this library as-is, since unnamed packages cannot be imported or referenced.

https://docs.oracle.com/javase/specs/jls/se6/html/packages.html

> It is a compile time error to import a type from the unnamed package.

**Comment by danielshaya** [comment]
Good point - this has been fixed and I've re-released with the change.

**Comment by nilskp** [comment]
Can you also release the jar? And preferably release on Bintray?

**Comment by danielshaya** [comment]
I've updated the 1.1 release with the jar.

Never used Bintray but will have look into it as soon as I get a chance. 

Thank you for your suggestions.
